name = "insulin-buddy-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
# Add your secrets via: wrangler secret put DISCORD_PUBLIC_KEY
# Add your secrets via: wrangler secret put N8N_WEBHOOK_URL
